name: Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: docker-react
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        run: docker build -t react-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run --rm -e CI=true react-test npm test

      - name: Create deploy bundle
        run: zip -r deploy.zip . -x '*.git*' -x 'node_modules/*' -x '.github/*'

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-north-1
      
      - name: Upload deploy bundle to S3 (EB bucket)
        run: aws s3 cp deploy.zip s3://elasticbeanstalk-eu-north-1-418272797873/docker/deploy-${{ github.sha }}-${{ github.run_number }}.zip


      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/aws-elasticbeanstalk-deploy@v1.0.0
        with:
          application-name: frontend
          environment-name: Frontend-env
          version-label: docker-${{ github.sha }}-${{ github.run_number }}
          deployment-package-path: deploy.zip
          aws-region: eu-north-1
          create-environment-if-not-exists: false
          create-application-if-not-exists: false